// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ichmyvtdcxkluxmjovnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljaG15dnRkY3hrbHV4bWpvdm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTA4ODgsImV4cCI6MjA3MzA4Njg4OH0.LLSicO2Mma2TJe7PlDRFL5p6xpTIm2XHP4uE37YhkH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});